'use client';

import { useState } from 'react';

interface ExecutiveSummaryProps {
  period?: string;
}

export function ExecutiveSummary({ period = 'February 2026' }: ExecutiveSummaryProps) {
  const [toast, setToast] = useState<string | null>(null);

  function showToast(msg: string) {
    setToast(msg);
    setTimeout(() => setToast(null), 3000);
  }

  return (
    <div style={{ position: 'relative' }}>
      {/* Toast */}
      {toast && (
        <div style={{
          position: 'fixed',
          bottom: '24px',
          right: '24px',
          padding: '12px 20px',
          background: 'var(--g900, #171717)',
          color: '#fff',
          borderRadius: '8px',
          fontSize: '13px',
          fontWeight: 500,
          zIndex: 1000,
          boxShadow: '0 4px 16px rgba(0,0,0,0.25)',
          animation: 'fadeIn 0.15s ease',
        }}>
          {toast}
        </div>
      )}

      <div style={{ background: '#fff', border: '1px solid var(--g200, #E8E8E8)', borderRadius: '10px', padding: '28px 32px', boxShadow: '0 1px 3px rgba(0,0,0,0.08)' }}>

        {/* Header row */}
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '20px', flexWrap: 'wrap', gap: '12px' }}>
          <div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '6px', flexWrap: 'wrap' }}>
              <span style={{
                padding: '2px 10px',
                borderRadius: '10px',
                fontSize: '11px',
                fontWeight: 700,
                background: 'var(--blue-light, #E8F6FA)',
                color: 'var(--blue-dark, #2A8BA8)',
                textTransform: 'uppercase',
                letterSpacing: '0.05em',
              }}>
                Generated by QM Orchestrator
              </span>
              <span style={{ fontSize: '12px', color: 'var(--g400, #A3A3A3)' }}>Feb 24, 2026 at 6:00 AM</span>
            </div>
            <h2 style={{ fontFamily: 'var(--font-source-serif-4, serif)', fontSize: '20px', fontWeight: 600, color: 'var(--g900, #171717)', margin: '0 0 2px' }}>
              {period} QM Executive Summary
            </h2>
            <p style={{ fontSize: '13px', color: 'var(--g500, #737373)', margin: 0 }}>
              Cholla Behavioral Health — IOP &amp; Residential Programs
            </p>
          </div>
          <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap' }}>
            <button
              onClick={() => showToast('PDF generation coming in Phase 5')}
              style={{
                padding: '7px 14px',
                background: '#fff',
                color: 'var(--g700, #404040)',
                border: '1px solid var(--g300, #D4D4D4)',
                borderRadius: '6px',
                fontSize: '13px',
                fontWeight: 500,
                cursor: 'pointer',
              }}
            >
              Export as PDF
            </button>
            <button
              onClick={() => showToast('Agent regeneration coming in Phase 4')}
              style={{
                padding: '7px 14px',
                background: 'var(--blue-bg, #F0F9FC)',
                color: 'var(--blue-dark, #2A8BA8)',
                border: '1px solid var(--blue-light, #E8F6FA)',
                borderRadius: '6px',
                fontSize: '13px',
                fontWeight: 500,
                cursor: 'pointer',
              }}
            >
              Regenerate Summary
            </button>
          </div>
        </div>

        <div style={{ borderTop: '1px solid var(--g100, #F5F5F5)', marginBottom: '20px' }} />

        {/* KPI row */}
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(130px, 1fr))', gap: '12px', marginBottom: '24px' }}>
          {[
            { label: 'Audit Readiness', value: '87%', color: '#16A34A', bg: '#F0FDF4' },
            { label: 'Checkpoints Done', value: '75%', color: '#D97706', bg: '#FFFBEB' },
            { label: 'Evidence Coverage', value: '88%', color: '#3BA7C9', bg: '#E8F6FA' },
            { label: 'CAPAs On Track', value: '66%', color: '#C05A2C', bg: '#FDF0EB' },
          ].map(({ label, value, color, bg }) => (
            <div key={label} style={{ padding: '14px 12px', background: bg, borderRadius: '8px', textAlign: 'center' }}>
              <p style={{ fontSize: '24px', fontWeight: 700, color, margin: '0 0 2px' }}>{value}</p>
              <p style={{ fontSize: '11px', color: 'var(--g500, #737373)', margin: 0 }}>{label}</p>
            </div>
          ))}
        </div>

        {/* Narrative */}
        <div style={{ fontSize: '14px', color: 'var(--g700, #404040)', lineHeight: '1.75', marginBottom: '20px', display: 'flex', flexDirection: 'column', gap: '12px' }}>
          <p style={{ margin: 0 }}>
            <strong>Compliance Performance:</strong> Cholla Behavioral Health completed 18 of 24 scheduled checkpoints for {period} (75%), with a 72% on-time completion rate.
            Audit readiness improved from 84% in January to <strong>87% this period</strong>, continuing a positive three-month trend.
            Six checkpoints remain in progress as of the meeting date; three are low-risk with evidence uploads pending.
          </p>
          <p style={{ margin: 0 }}>
            <strong>Key Findings:</strong> Three findings require board attention this period.
            The fire drill for the Residential facility was conducted on February 10 but documentation is incomplete, creating a Safety/NFPA deficiency.
            The Policy Guardian agent flagged a cross-policy conflict: the draft Telehealth Service Delivery policy (POL-CLN-002) references a digital consent process not defined in the Consent Procedures policy.
            The Medication Storage CAPA (CAPA-2026-003) is overdue by five days and requires immediate owner escalation.
          </p>
          <p style={{ margin: 0 }}>
            <strong>Positive Indicators:</strong> The IOP Chart Audit achieved a <strong>100% pass rate</strong> for the third consecutive month.
            HIPAA safeguards audit was completed with zero findings. OIG screening is current for all staff and contractors.
          </p>
        </div>

        {/* Recommendations */}
        <div style={{ marginBottom: '24px' }}>
          <h3 style={{ fontSize: '12px', fontWeight: 700, color: 'var(--g500, #737373)', textTransform: 'uppercase', letterSpacing: '0.06em', margin: '0 0 10px' }}>
            Recommended Actions
          </h3>
          <ol style={{ margin: 0, paddingLeft: '20px', display: 'flex', flexDirection: 'column', gap: '8px' }}>
            {[
              'Escalate CAPA-2026-003 to James Williams immediately — medication temperature logging overdue since Feb 20.',
              'Conduct new fire drill at Residential facility with complete documentation protocol by March 15.',
              'Resolve Telehealth ↔ Consent Policy cross-reference conflict before approving POL-CLN-002.',
              'Accept Compliance Monitor suggestion to formalize digital temperature logging as a monthly control.',
            ].map((rec, i) => (
              <li key={i} style={{ fontSize: '14px', color: 'var(--g700, #404040)', lineHeight: '1.5' }}>
                {rec}
              </li>
            ))}
          </ol>
        </div>

        {/* Trend chart */}
        <div style={{ background: 'var(--g50, #FAFAFA)', border: '1px solid var(--g200, #E8E8E8)', borderRadius: '8px', padding: '16px 20px' }}>
          <p style={{ fontSize: '12px', fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.05em', color: 'var(--g500, #737373)', margin: '0 0 12px' }}>
            Audit Readiness Trend — Last 3 Periods
          </p>
          <div style={{ display: 'flex', alignItems: 'flex-end', gap: '16px', height: '56px' }}>
            {[
              { period: 'Dec 2025', score: 82 },
              { period: 'Jan 2026', score: 84 },
              { period: 'Feb 2026', score: 87 },
            ].map(({ period: p, score }, i, arr) => (
              <div key={p} style={{ flex: 1, display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '4px' }}>
                <span style={{ fontSize: '13px', fontWeight: 700, color: i === arr.length - 1 ? 'var(--blue, #3BA7C9)' : 'var(--g600, #525252)' }}>
                  {score}%
                </span>
                <div style={{
                  width: '100%',
                  height: `${(score / 100) * 36}px`,
                  background: i === arr.length - 1 ? 'var(--blue, #3BA7C9)' : 'var(--blue-light, #E8F6FA)',
                  borderRadius: '3px 3px 0 0',
                }} />
                <span style={{ fontSize: '11px', color: 'var(--g400, #A3A3A3)', textAlign: 'center' }}>{p}</span>
              </div>
            ))}
          </div>
          <p style={{ fontSize: '12px', color: 'var(--green, #16A34A)', margin: '10px 0 0', fontWeight: 600 }}>
            ↑ On track for full readiness by Q2 2026
          </p>
        </div>
      </div>
    </div>
  );
}
