'use client';

import { useState, useEffect, useCallback } from 'react';
import { useRouter } from 'next/navigation';
import { createClient } from '@/lib/supabase/client';

export interface FindingItem {
  id: string;
  severity: 'critical' | 'high' | 'medium' | 'low';
  title: string;
  description: string;
  checkpoint?: string | null;
  standard: string;
  isPositive?: boolean;
  isAutoGenerated?: boolean;
}

const SEV_CONFIG: Record<string, { bg: string; borderColor: string; color: string; headerBg: string; label: string }> = {
  critical: { bg: '#FEF2F2', borderColor: '#DC2626', color: '#DC2626', headerBg: '#FEE2E2', label: 'Critical' },
  high:     { bg: '#FDF0EB', borderColor: '#C05A2C', color: '#C05A2C', headerBg: '#FBDDD0', label: 'High' },
  medium:   { bg: '#FFFBEB', borderColor: '#D97706', color: '#D97706', headerBg: '#FEF3C7', label: 'Medium' },
  low:      { bg: '#F0FDF4', borderColor: '#16A34A', color: '#16A34A', headerBg: '#DCFCE7', label: 'Low' },
};

const STD_COLORS: Record<string, { bg: string; color: string }> = {
  Safety:   { bg: '#FFFBEB', color: '#B45309' },
  AHCCCS:   { bg: '#F0FDF4', color: '#15803D' },
  HIPAA:    { bg: '#F5F3FF', color: '#6D28D9' },
  OIG:      { bg: '#EFF6FF', color: '#1D4ED8' },
  TJC:      { bg: '#FDF4FF', color: '#7E22CE' },
  CARF:     { bg: '#FFF7ED', color: '#C2410C' },
  Internal: { bg: '#F5F5F5', color: '#525252' },
};

interface DBFinding {
  id: string;
  title: string;
  description?: string;
  severity: 'critical' | 'high' | 'medium' | 'low';
  standard?: string;
  checkpoint?: {
    period: string;
    control?: { code: string } | null;
  } | null;
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
interface DBCheckpoint {
  id: string;
  status: string;
  period: string;
  control?: { code: string; title: string; standard: string } | null;
}

function transformFinding(f: DBFinding): FindingItem {
  return {
    id: f.id,
    severity: f.severity,
    title: f.title,
    description: f.description ?? '',
    checkpoint: f.checkpoint
      ? `${f.checkpoint.control?.code ?? 'Checkpoint'} — ${f.checkpoint.period}`
      : null,
    standard: f.standard ?? 'Internal',
    isPositive: false,
    isAutoGenerated: false,
  };
}

function checkpointToFinding(cp: DBCheckpoint): FindingItem {
  return {
    id: `auto-${cp.id}`,
    severity: cp.status === 'failed' ? 'high' : 'medium',
    title: `${cp.status === 'failed' ? 'Failed' : 'Overdue'}: ${cp.control?.title ?? 'Unknown Control'}`,
    description: `Checkpoint ${cp.control?.code ?? ''} was ${cp.status} for period ${cp.period}.`,
    checkpoint: `${cp.control?.code ?? 'Checkpoint'} — ${cp.period}`,
    standard: cp.control?.standard ?? 'Internal',
    isPositive: false,
    isAutoGenerated: true,
  };
}

interface FindingsGridProps {
  findings?: FindingItem[];
  onCreateCAPA?: (findingId: string, title: string) => void;
  meetingId?: string;
  orgId?: string;
  period?: string;
  onFindingCreated?: () => void;
}

const EMPTY_FORM = { title: '', description: '', severity: 'medium', standard: '' };

export function FindingsGrid({ findings, onCreateCAPA, meetingId, orgId, period, onFindingCreated }: FindingsGridProps) {
  const router = useRouter();
  const [dbFindings, setDbFindings] = useState<FindingItem[]>([]);
  const [autoFindings, setAutoFindings] = useState<FindingItem[]>([]);
  const [loading, setLoading] = useState(false);
  const [showNewForm, setShowNewForm] = useState(false);
  const [newForm, setNewForm] = useState(EMPTY_FORM);
  const [submitting, setSubmitting] = useState(false);
  const [toast, setToast] = useState<string | null>(null);

  // Merge manual + auto-generated findings
  const displayFindings = findings ?? [...autoFindings, ...dbFindings];

  // Fetch manual findings from DB
  const fetchFindings = useCallback(async () => {
    if (!meetingId || !orgId || findings) return;
    setLoading(true);
    const supabase = createClient();
    const { data } = await supabase
      .from('findings')
      .select('*, checkpoint:checkpoints(period, control:controls(code))')
      .eq('org_id', orgId)
      .eq('qm_meeting_id', meetingId)
      .order('created_at', { ascending: false });
    setDbFindings((data ?? []).map(transformFinding));
    setLoading(false);
  }, [meetingId, orgId, findings]);

  // Fetch failed/overdue checkpoints for this period → auto-generate findings
  const fetchCheckpointFindings = useCallback(async () => {
    if (!orgId || !period || findings) return;
    const supabase = createClient();
    const { data } = await supabase
      .from('checkpoints')
      .select('id, status, period, control:controls(code, title, standard)')
      .eq('org_id', orgId)
      .eq('period', period)
      .in('status', ['failed', 'overdue']);

    if (data) {
      setAutoFindings(data.map((cp: unknown) => checkpointToFinding(cp as DBCheckpoint)));
    }
  }, [orgId, period, findings]);

  useEffect(() => { fetchFindings(); }, [fetchFindings]);
  useEffect(() => { fetchCheckpointFindings(); }, [fetchCheckpointFindings]);

  function showToast(msg: string) {
    setToast(msg);
    setTimeout(() => setToast(null), 3000);
  }

  async function handleCreateCAPA(findingId: string, title: string) {
    if (onCreateCAPA) {
      onCreateCAPA(findingId, title);
      return;
    }
    if (orgId) {
      const supabase = createClient();
      const { data: capa } = await supabase
        .from('capas')
        .insert({ org_id: orgId, finding_id: findingId, title: `CAPA: ${title}`, status: 'open' })
        .select('id')
        .single();
      if (capa) {
        router.push(`/capa/${capa.id}`);
        return;
      }
    }
    router.push('/capa');
  }

  async function submitFinding() {
    if (!orgId || !meetingId || !newForm.title.trim()) return;
    setSubmitting(true);
    const supabase = createClient();
    const { data } = await supabase
      .from('findings')
      .insert({
        org_id: orgId,
        qm_meeting_id: meetingId,
        title: newForm.title.trim(),
        description: newForm.description.trim() || null,
        severity: newForm.severity,
        standard: newForm.standard.trim() || null,
      })
      .select('*, checkpoint:checkpoints(period, control:controls(code))')
      .single();
    if (data) {
      setDbFindings((prev) => [transformFinding(data as DBFinding), ...prev]);
      onFindingCreated?.();
      showToast('Finding added');
    }
    setNewForm(EMPTY_FORM);
    setShowNewForm(false);
    setSubmitting(false);
  }

  if (loading) {
    return <div style={{ padding: '32px', textAlign: 'center', color: 'var(--g400, #A3A3A3)', fontSize: '14px' }}>Loading findings...</div>;
  }

  return (
    <div>
      {toast && (
        <div style={{ position: 'fixed', bottom: '24px', right: '24px', padding: '12px 20px', background: 'var(--g900, #171717)', color: '#fff', borderRadius: '8px', fontSize: '13px', fontWeight: 500, zIndex: 1000, boxShadow: '0 4px 16px rgba(0,0,0,0.25)' }}>
          {toast}
        </div>
      )}

      {/* Header with Add button */}
      {meetingId && orgId && (
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px' }}>
          {autoFindings.length > 0 && (
            <p style={{ fontSize: '13px', color: 'var(--g500, #737373)', margin: 0 }}>
              {autoFindings.length} auto-generated from failed/overdue checkpoints
            </p>
          )}
          <div style={{ marginLeft: 'auto' }}>
            <button
              onClick={() => setShowNewForm(!showNewForm)}
              style={{ padding: '7px 16px', background: showNewForm ? '#fff' : 'var(--blue, #3BA7C9)', color: showNewForm ? 'var(--g700, #404040)' : '#fff', border: '1px solid var(--g300, #D4D4D4)', borderRadius: '6px', fontSize: '13px', fontWeight: 600, cursor: 'pointer' }}
            >
              {showNewForm ? 'Cancel' : '+ Add Finding'}
            </button>
          </div>
        </div>
      )}

      {/* New finding form */}
      {showNewForm && (
        <div style={{ background: '#fff', border: '1px solid var(--g200, #E8E8E8)', borderRadius: '10px', padding: '20px 24px', marginBottom: '16px', boxShadow: '0 1px 3px rgba(0,0,0,0.06)' }}>
          <h3 style={{ fontSize: '14px', fontWeight: 600, color: 'var(--g800, #262626)', margin: '0 0 16px' }}>New Finding</h3>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
            <input
              value={newForm.title}
              onChange={(e) => setNewForm((f) => ({ ...f, title: e.target.value }))}
              placeholder="Finding title (required)"
              style={{ padding: '8px 12px', border: '1px solid var(--g300, #D4D4D4)', borderRadius: '6px', fontSize: '13px', outline: 'none' }}
            />
            <textarea
              value={newForm.description}
              onChange={(e) => setNewForm((f) => ({ ...f, description: e.target.value }))}
              placeholder="Description..."
              rows={3}
              style={{ padding: '8px 12px', border: '1px solid var(--g300, #D4D4D4)', borderRadius: '6px', fontSize: '13px', resize: 'vertical', outline: 'none', fontFamily: 'inherit' }}
            />
            <div style={{ display: 'flex', gap: '12px', flexWrap: 'wrap' }}>
              <select
                value={newForm.severity}
                onChange={(e) => setNewForm((f) => ({ ...f, severity: e.target.value }))}
                style={{ padding: '7px 12px', border: '1px solid var(--g300, #D4D4D4)', borderRadius: '6px', fontSize: '13px', background: '#fff', flex: 1 }}
              >
                {['critical', 'high', 'medium', 'low'].map((s) => (
                  <option key={s} value={s}>{s.charAt(0).toUpperCase() + s.slice(1)}</option>
                ))}
              </select>
              <input
                value={newForm.standard}
                onChange={(e) => setNewForm((f) => ({ ...f, standard: e.target.value }))}
                placeholder="Standard (e.g., HIPAA)"
                style={{ padding: '8px 12px', border: '1px solid var(--g300, #D4D4D4)', borderRadius: '6px', fontSize: '13px', outline: 'none', flex: 1 }}
              />
            </div>
            <div style={{ display: 'flex', gap: '8px' }}>
              <button
                onClick={submitFinding}
                disabled={submitting || !newForm.title.trim()}
                style={{ padding: '8px 20px', background: 'var(--blue, #3BA7C9)', color: '#fff', border: 'none', borderRadius: '6px', fontSize: '13px', fontWeight: 600, cursor: submitting || !newForm.title.trim() ? 'default' : 'pointer', opacity: submitting || !newForm.title.trim() ? 0.6 : 1 }}
              >
                {submitting ? 'Adding...' : 'Add Finding'}
              </button>
            </div>
          </div>
        </div>
      )}

      {displayFindings.length === 0 ? (
        <div style={{ background: '#fff', border: '1px solid var(--g200, #E8E8E8)', borderRadius: '10px', padding: '40px', textAlign: 'center' }}>
          <p style={{ fontSize: '14px', color: 'var(--g400, #A3A3A3)', margin: 0 }}>
            No findings recorded for this meeting.{meetingId ? ' Use "+ Add Finding" to record one.' : ''}
          </p>
        </div>
      ) : (
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(340px, 1fr))', gap: '16px' }}>
          {displayFindings.map((finding) => {
            const cfg = SEV_CONFIG[finding.severity];
            const std = STD_COLORS[finding.standard] ?? { bg: '#F5F5F5', color: '#525252' };
            return (
              <div
                key={finding.id}
                style={{
                  background: cfg.bg,
                  border: `1px solid ${cfg.borderColor}30`,
                  borderTop: `3px solid ${cfg.borderColor}`,
                  borderRadius: '10px',
                  overflow: 'hidden',
                  boxShadow: '0 1px 3px rgba(0,0,0,0.06)',
                }}
              >
                <div style={{ padding: '16px 18px' }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '10px', flexWrap: 'wrap', gap: '6px' }}>
                    <div style={{ display: 'flex', gap: '4px', flexWrap: 'wrap' }}>
                      <span style={{ padding: '2px 10px', borderRadius: '10px', fontSize: '11px', fontWeight: 700, background: cfg.headerBg, color: cfg.color, textTransform: 'uppercase', letterSpacing: '0.05em' }}>
                        {cfg.label}
                      </span>
                      {finding.isAutoGenerated && (
                        <span style={{ padding: '2px 8px', borderRadius: '10px', fontSize: '11px', fontWeight: 600, background: '#E8F6FA', color: '#0E7490' }}>
                          Auto
                        </span>
                      )}
                    </div>
                    <div style={{ display: 'flex', gap: '4px' }}>
                      <span style={{ padding: '2px 8px', borderRadius: '10px', fontSize: '11px', fontWeight: 600, background: std.bg, color: std.color }}>
                        {finding.standard}
                      </span>
                    </div>
                  </div>

                  <h3 style={{ fontSize: '14px', fontWeight: 600, color: 'var(--g900, #171717)', margin: '0 0 8px' }}>
                    {finding.title}
                  </h3>
                  <p style={{ fontSize: '13px', color: 'var(--g700, #404040)', margin: '0 0 12px', lineHeight: '1.55' }}>
                    {finding.description}
                  </p>

                  {finding.checkpoint && (
                    <p style={{ fontSize: '12px', color: 'var(--g500, #737373)', margin: '0 0 12px' }}>
                      <span style={{ fontWeight: 500 }}>Checkpoint: </span>{finding.checkpoint}
                    </p>
                  )}

                  {!finding.isPositive && !finding.isAutoGenerated && (
                    <button
                      onClick={() => handleCreateCAPA(finding.id, finding.title)}
                      style={{ padding: '6px 14px', background: 'var(--blue, #3BA7C9)', color: '#fff', border: 'none', borderRadius: '6px', fontSize: '12px', fontWeight: 600, cursor: 'pointer' }}
                    >
                      Create CAPA
                    </button>
                  )}
                  {finding.isAutoGenerated && (
                    <p style={{ fontSize: '11px', color: 'var(--g400, #A3A3A3)', margin: 0, fontStyle: 'italic' }}>
                      Generated from calendar checkpoint data
                    </p>
                  )}
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
